### ISSUE TITLE
Chapter 8/Run Example doesn't use ticks, but `go` waits on reset ticks

### ISSUE THREAD

**Issue by qiemem** [NetLogo/models#60] opened 2015-05-26 01:28 UTC
It should probably just use ticks

**Comment by nicolaspayette** [comment] 2015-05-26 01:39
Thanks for the report!

It's a duplicate of https://github.com/NetLogo/models/issues/50 and already fixed in the repo. It's also on my list of models to convert in https://github.com/NetLogo/models/issues/58.

**Comment by qiemem** [comment] 2015-05-26 01:40
Damnit, I should really check that kind of thing first. Sorry about that!

**Closed by nicolaspayette** 2015-05-26 01:39 UTC

**Comment by nicolaspayette** [comment] 2015-05-26 01:40
I much prefer a duplicate report than no report at all! :-)
