### ISSUE TITLE
BeeSmart 2nd model

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/models#135] opened 2015-09-24 14:44 UTC
@toxy100 how is your checkout going? did you make the revisions that Nicolas suggested? we're aiming to release today or tomorrow.

**Comment by nicolaspayette** [comment] 2015-09-24 14:45
Duplicate of #124.

**Comment by arthurhjorth** [comment] 2015-09-24 14:46
Whoops, I am not sure how, but I dup... Nicolas beat me to it. THanks.

**Comment by nicolaspayette** [comment] 2015-09-24 14:46
:-)

**Closed by nicolaspayette** 2015-09-24 14:45 UTC
